// 定義錯誤enum管理，不要用字串/手寫輸入
export enum ErrorCode {
    INVALID_ASSET_ID = "INVALID_ASSET_ID",
    INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY",
    ASSET_NOT_FOUND = "ASSET_NOT_FOUND",
    ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
}